return {
	-- {
	  -- 'kristijanhusak/vim-dadbod-ui',
	  -- dependencies = {
		-- { 'tpope/vim-dadbod', lazy = true },
		-- { 'kristijanhusak/vim-dadbod-completion', ft = { 'sql', 'mysql', 'plsql' }, lazy = true }, -- Optional
	  -- },
	  -- cmd = {
		-- 'DBUI',
		-- 'DBUIToggle',
		-- 'DBUIAddConnection',
		-- 'DBUIFindBuffer',
	  -- },
	  -- init = function()
		--Your DBUI configuration
		-- vim.g.db_ui_use_nerd_fonts = 1
	  -- end,
	  -- vim.g.dbs = {
		-- \ 'dev': 'LOLOT430\SQLEXPRESS01',
		--\ 'staging': 'postgres://postgres:mypassword@localhost:5432/my-staging-db',
		-- \ 'wp': 'mysql://root@localhost/wp_awesome',
		-- \ 'production': function('s:resolve_production_url')
	-- \ }
  -- }
}